### ISSUE TITLE
デザイン2　パターンの方針決め

### ISSUE THREAD

**Issue by KuraJin01Fate** [ponkotuandroid/ChinpannKrajin#5]
* [x] A 案
* [x] B 案

**Comment by uezonokou** [comment]
おれはC案がいいです

**Comment by uezonokou** [comment]
渋谷凛です

**Comment by KuraJin01Fate** [comment]
だめ（ない）です

**Comment by uihgdr75** [comment]
もう一声！

**Comment by uihgdr75** [comment]
やる気あんのか？

**Comment by uezonokou** [comment]
プロデューサー、しっかりしてよ（CV:福原綾香)

**Comment by uihgdr75** [comment]
違うだろー

**Comment by uezonokou** [comment]
このハゲー

**Comment by uihgdr75** [comment]
私が泣きたいよ

**Comment by uezonokou** [comment]
おなかすいたんご

**Comment by KuraJin01Fate** [comment]
とうもろこしくっとけ

**Comment by uihgdr75** [comment]
お前は私の心を叩いている！！！

**Comment by uezonokou** [comment]
私、Triad Primusに行くよ。

**Comment by uihgdr75** [comment]
豊田真由子衆議院議員が元秘書に「このハゲー」と暴言とともに暴行を起こした騒動に秘書がコメントをした。
そのコメントが秀逸だとネットで話題となっている。

秘書が語ったとされる内容がコレだ。

「豊田はウソばかり言っていますが、ひとつだけ正しい。それは、私が確かにハゲている、ということです」

**Comment by uezonokou** [comment]
しっかりしてよ、プロデューサー

**Comment by uezonokou** [comment]
@uihgdr75 このハゲー

**Comment by KuraJin01Fate** [comment]
@sauenoue2525 判断はお前にゆだねられた

**Comment by uihgdr75** [comment]
■火に油を注いだ“お詫び”

事件が表沙汰になった６月初旬以降、豊田議員は男性秘書に計３回「お詫び」したらしいが、事態は一向に収まる気配がない。
一体、どんなやりとりがあったのか。男性秘書を直撃した。

「そもそも私がメディアの取材に応じたのは、国会議員・豊田真由子の“全て”を有権者の方に知らせるべきだと思ったからです。
人間誰しも表と裏の顔があり、国会議員であればなおさらでしょう。しかし、豊田の“裏の顔”は度を越していました。
お詫びの言葉めいたことを直接言われましたが、豊田は『感情が高ぶっていたせいで覚えていない』と言うわけです。
本人が覚えていないことを、私が許すことなんてできません。
なにより自身の暴力や暴言に関して反省しているようには見受けられませんでした。
もし豊田が事実を否認し続けたら、法廷で争います。
また、非を認め謝罪されたとしても、私は示談に応じるつもりはありません。
ごく当たり前のことですが、日本の法体系に基づいて、粛々と処罰を受けるべきです」

どうやら、豊田議員は「何がいけないのか分からないけど、大騒ぎになっているからお詫びするよ」という態度だったらしい。
しかも、「覚えていない」という。これじゃあ男性秘書の腹の虫が治まらないのも当然だ。

一方、一部では男性秘書が積極的にマスコミにネタを売り込んだのではないのか――なんて声もあったが、事実は違うようだ。
パワハラ事件の全容を知る関係者がコトの経緯について、こう明かした。

「週刊誌へ豊田の暴言をリークしたのは被害を受けた本人ではありません。
彼は、あくまで、メディアが取材に来たら応じようというスタンスで、自ら“ネタ”を持ち込んだわけではないのです。
過去に辞めていった秘書の誰かが、タレ込んだんじゃないですか。辞めていった秘書の多くが泣き寝入りしていますから。
豊田はどこにいるか分かりませんが、『録音されたのは私の声じゃない』とか、『秘書にはめられた』と言っているようです」

豊田議員は一体、どこに雲隠れしているのか。
あらためて男性秘書に豊田議員に言いたいことを尋ねると、力なくつぶやいた。

「豊田はウソばかり言っていますが、ひとつだけ正しい。
それは、私が確かにハゲている、ということです」

これには本紙記者もハゲましの言葉をかけることはできなかった……。

**Comment by sauenoue2525** [comment]
なんでもいいよ

**Comment by uezonokou** [comment]
やめんか

**Comment by uezonokou** [comment]
奈緒をモフモフしたい

**Comment by uihgdr75** [comment]
ハゲ増し

**Comment by uezonokou** [comment]
草

**Comment by uihgdr75** [comment]
お前が受けた痛みは何だ？

私が受けた痛みのどのくらいわかるか？

このやろう！

**Comment by uihgdr75** [comment]
お前はどれだけ私の心を叩いている？

わかってないよ！

お前はどれだけ私の心を叩いている？

これ以上、私の評判をさげるな！

これ以上、私の評判を下げるな！

私の心を傷つけるな！

これ以上、私の支援者を怒らせるな！

お前がたたくよりよっぽど痛いよ！

たたいていいよ！私の事！

そっちのほうがよっぽど楽だよ！

たたかれるほうがよっぽど楽だよ！

たたいていいよ！私の事！

だから頼むから支援者を怒らせるな！

支援者をおこらせるな！頼むから！

**Comment by uezonokou** [comment]
# ****やめたげろ

**Comment by uezonokou** [comment]
**はらへった**

**Comment by uihgdr75** [comment]
@KuraJin01Fate # このやろう！

**Comment by uezonokou** [comment]
@KuraJin01Fate なんとか言えよ

**Comment by KuraJin01Fate** [comment]
草草の草

**Comment by uezonokou** [comment]
おわ
